# Site settings
title: Rust Iran Meetup
description: "A monthly meetup on Rust lang in Iran"
baseurl: ""
url: "https://rust-meetup.ir"
author:
  name: Hamid R. K. Pishghadam 
  twitter: Rust_ir
  github: rust-meetup/rust-meetup.ir
  telegram: Rustland
  email: kaveh@riseup.net

feedback_url: https://github.com/rust-meetup/rust-meetup.ir
source_repo: rust-meetup/rust-meetup.ir

google_maps_api_key: AIzaSyBkz492n9gf895Tfi12ikKVurgIHHOFmK4

# Build settings
permalink: "/:year/:month/:day/:title.html"
markdown: kramdown
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "event"

# Content settings
future: true # we use dates for the actual meetup time, not the post publication time
timezone: "Asia/Tehran"

exclude:
  - .vscode
  - .gitignore
  - meetup-orga
